<?php
$msg = '<table width="100%" border="0" cellspacing="0" cellpadding="0" style="background-color:#EF2C2B">
  <tbody>
    <tr>
      <td height="900" align="center" valign="middle">
      <table width="700" border="0" cellspacing="0" cellpadding="12" style="background-color: #fff; border: #900000 solid 1px; font-family: \'Lucida Grande\', \'Lucida Sans Unicode\', \'Lucida Sans\', \'DejaVu Sans\', Verdana, sans-serif; color: #0F0E0E; font-style: normal; font-weight: 400; line-height: 24px; font-size: 15px;">
        <tbody>
          <tr>
            <td width="313" style="background: #FFD67C; border-bottom: #900000 solid 1px;"><img src="'.$urlLogo.'assets/img/logo.png"
            alt=""/></td>
            <td width="337" style="background: #FFD67C; border-bottom: #900000 solid 1px;"><p style="text-align:right;
            font-size:24px; font-weight:700;
            font-family:\'Lucida Grande\', \'Lucida Sans Unicode\', \'Lucida Sans\', \'DejaVu Sans\', Verdana, sans-serif; letter-spacing:-0.05em">Recebemos o seu contato!</p></td>
          </tr>
          <tr>
            <td colspan="2">Ol&aacute; <strong>'.$nome.'</strong>,</td>
            </tr>
          <tr>
            <td colspan="2">
              <p>Recebemos a sua solicita&ccedil;&atilde;o de contato.</p>
              <p>Junto, enviou estes dados:<br>
                Nome: <strong style="color:#016faf;">'.$nome.'</strong><br>
                E-mail: <strong style="color:#016faf;">'.$email.'</strong><br>
                Telefone: <strong style="color:#016faf;">'.$telefone.'</strong><br>
                Como nos Conheceu: <strong style="color:#016faf;">'.$conheceu.'</strong><br>
                Mensagem: <br><strong style="color:#016faf;">'.$mensagem.'</strong><br>
              </p>
              <p>Em breve retornaremos para um dos canais que nos enviou para contato.</p>

            </td>
            </tr>
          <tr>
            <td colspan="2">
              <p><small>Atencionamente</small><br>
                <a href="'.$urlLogo.'" target="_blank"><strong style="color:#016faf;">Equipe</strong></a>
              </p>
            </td>
            </tr>
        </tbody>
      </table></td>
    </tr>
  </tbody>
</table>';